#!/usr/bin/env bash

apt-get -y update
apt-get -y install nginx

# url cible
ytb="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Replace config 
trn="location /redirect_me {
    return 301 $ytb;
}"

# config file
file="/etc/nginx/sites-available/default"

sudo sed -i "/location \/ {/a\
	$trn/  $file"

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apppply the changes
systemctl start nginx
