#!/usr/bin/env bash                                                                                                                                                                     
# redirection to ytb                                                                                                                                                                    
apt-get -y update                                                                                                                                                                       
apt-get -y install nginx                                                                                                                                                                
echo "Hello World!" > /var/www/html/index.html                                                                                                                                          
# url cible                                                                                                                                                                             
ytb="error_page 404 /erri100.html; \n\tlocation = /erri100.html {\n\t\tinternal;\n\t}"                                                                                                  
#touch /var/www/html/erri100.html                                                                                                                                                       
echo "Ceci n'est pas une page" >  /var/www/html/erri100.html                                                                                                                            
bv="https://www.youtube.com/watch?v=QH2-TGUlwu4"                                                                                                                                        
fichier="/etc/nginx/sites-available/default"                                                                                                                                            
#trnsf="root /var/www/html;"                                                                                                                                                            
#echo "Ceci n'est pas une page" > /var/www/html/index.html                                                                                                                              
                                                                                                                                                                                        
sed -i "\%^\troot /var/www/html;%a\ \tlocation /redirect_me { return 301 $bv;}" $fichier                                                                                                
                                                                                                                                                                                        
#etc/nginx/sites-available/                                                                                                                                                             
# config cible                                                                                                                                                                          
#trn="location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"                                                                                                 
                                                                                                                                                                                        
#}"                                                                                                                                                                                     
                                                                                                                                                                                        
# path file                                                                                                                                                                             
file="/etc/nginx/sites-available/default"                                                                                                                                               
                                                                                                                                                                                        
#sudo sed -i "/ location / {/a\                                                                                                                                                         
#$trn" $file                                                                                                                                                                            
                                                                                                                                                                                        
#sed -i "\%^\troot /var/www/html;%a\ \tlocation /redirect_me { return 301 $bv;}" $file                                                                                                  
sed -i "\%^\troot /var/www/html;%a\ \t$ytb" $file                                                                                                                                       
                                                                                                                                                                                        
# Test the Nginx configuration                                                                                                                                                          
nginx -t                                                                                                                                                                                
                                                                                                                                                                                        
# Reload Nginx to apppply the changes                                                                                                                                                   
service nginx restart  
