#!/usr/bin/env bash
#HAproxyyiy
apt-get update
apt-get install nginx
apt-get install haproxy
echo "ENABLED=1" > /etc/default/haproxy

echo "
frontend http_front
    bind *:80
    default_backend http_rear

backend http_rear
    balance roundrobin
    server 387178-web-01 100.25.19.136:80 check
    server 387178-web-02 35.174.205.13:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
