#!/usr/bin/env bash
#Bash script that displays a list of currently running processes.
# Affiche les en-têtes du tableau
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Récupère les informations sur les processus en cours d'exécution
ps -ef --forest | awk 'NR > 1 { print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11 }'
